[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@commandbar/netlify-plugin-commandbar"

[plugins.inputs]
  entryPoint = "iindex.html"

[plugins.inputs.linkCommands]
  "Go to stack overflow" = 'https://stackoverflow.com'

[[plugins]]
  package = "@netlify/plugin-nextjs"
