[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@commandbar/netlify-plugin-commandbar"

# Optional
entryPoint = "index.html"

[plugins.inputs.linkCommands]
  "Go to stack overflow" = 'https://stackoverflow.com'

[[plugins]]
  package = "@netlify/plugin-nextjs"
